services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tickets
    restart: always
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - tickets-network

  api:
    image: ghcr.io/gtomanini/tickets-system-api:latest
    container_name: api-tickets
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/tickets
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - tickets-network

volumes:
  mysql-data:

networks:
  tickets-network:
