version: '1.0'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tickets
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'tickets'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_USER: admin
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tickets
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
